export { default as WorkspaceSwitcher } from './WorkspaceSwitcher'
export { default as WorkspaceShell } from './WorkspaceShell'
export * from './widgetCatalog'
export * from './workspaceAiContext'
export * from './workspaceLayoutStorage'
export * from './workspaceRegistry'
export * from './workspaceCustomization'
